function createfigure(X1, Y1, xlabl, ylabl)
%CREATEFIGURE(X1, Y1, X2, X3, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 30-Jul-2018 21:59:19

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[0 1 1]);

% Create ylabel
ylabel(ylabl,'FontWeight','bold','FontSize',16);

% Create xlabel
xlabel(xlabl,'FontWeight','bold','FontSize',16);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 40]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 18000]);
% Set the remaining axes properties
set(axes1,'FontSize',12,'XGrid','on','XMinorGrid','on','YGrid','on',...
    'YMinorGrid','on');
